
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:OutpostOmega.Drawing.UI.Load.adressBackButton_Clicked(Gwen.Control.Base,Gwen.Control.ClickedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:OutpostOmega.Drawing.UI.Load.listBox_DoubleClicked(Gwen.Control.Base,Gwen.Control.ClickedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:OutpostOmega.Drawing.UI.Load.listBox_RowSelected(Gwen.Control.Base,Gwen.Control.ItemSelectedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:OutpostOmega.Drawing.UI.Load.loadFiles")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:OutpostOmega.Drawing.UI.Load.okButton_Clicked(Gwen.Control.Base,Gwen.Control.ClickedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:OutpostOmega.Drawing.Game.WorldDrawer.nStructure_newChunk(OutpostOmega.Game.turf.Chunk)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:OutpostOmega.Drawing.UI.MainMenu.continueWorld_Clicked(Gwen.Control.Base,Gwen.Control.ClickedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:OutpostOmega.Drawing.UI.MainMenu.exit_Pressed(Gwen.Control.Base,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:OutpostOmega.Drawing.UI.MainMenu.load_Clicked(Gwen.Control.Base,Gwen.Control.ClickedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:OutpostOmega.Drawing.UI.MainMenu.multiplayer_Clicked(Gwen.Control.Base,Gwen.Control.ClickedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:OutpostOmega.Drawing.UI.MainMenu.newWorld_Clicked(Gwen.Control.Base,Gwen.Control.ClickedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:OutpostOmega.Drawing.UI.MainMenu.options_Clicked(Gwen.Control.Base,Gwen.Control.ClickedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:OutpostOmega.Drawing.UI.MenuBar.console_Clicked(Gwen.Control.Base,Gwen.Control.ClickedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:OutpostOmega.Drawing.UI.MenuBar.debug_Clicked(Gwen.Control.Base,Gwen.Control.ClickedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:OutpostOmega.Drawing.UI.MenuBar.exit_Pressed(Gwen.Control.Base,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:OutpostOmega.Drawing.UI.MenuBar.fullScreen_Clicked(Gwen.Control.Base,Gwen.Control.ClickedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:OutpostOmega.Drawing.UI.MenuBar.options_Clicked(Gwen.Control.Base,Gwen.Control.ClickedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:OutpostOmega.Drawing.UI.MenuBar.performance_Clicked(Gwen.Control.Base,Gwen.Control.ClickedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:OutpostOmega.Drawing.UI.MenuBar.reset_Clicked(Gwen.Control.Base,Gwen.Control.ClickedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:OutpostOmega.Drawing.UI.MenuBar.save_Clicked(Gwen.Control.Base,Gwen.Control.ClickedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:OutpostOmega.Drawing.UI.MenuBar.videoPlayer_Clicked(Gwen.Control.Base,Gwen.Control.ClickedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:OutpostOmega.Drawing.UI.ToolBar.cont_Clicked(Gwen.Control.Base,Gwen.Control.ClickedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:OutpostOmega.Drawing.UI.ToolBar.exit_Pressed(Gwen.Control.Base,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:OutpostOmega.Drawing.UI.ToolBar.reset_Clicked(Gwen.Control.Base,Gwen.Control.ClickedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:OutpostOmega.Drawing.UI.ToolBar.save_Clicked(Gwen.Control.Base,Gwen.Control.ClickedEventArgs)")]